# Generated by Django 5.0.6 on 2024-06-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(max_length=40)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('cod_caja', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('peso', models.CharField(max_length=3)),
                ('empresa', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
    ]
