# Generated by Django 5.0.6 on 2024-07-14 22:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webveguita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='fecha_recepcion',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='cod_caja',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='boleta',
            name='fecha_compra',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='boleta',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cajas',
            name='dimension',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajas',
            name='id_caja',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajas',
            name='tipo_caja',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default=0, max_length=200, verbose_name='Correo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id_boleta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='Detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webveguita.boleta')),
                ('id_caja', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webveguita.cajas')),
            ],
        ),
    ]
